# Generated by Django 4.0 on 2021-12-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_agent_name_alter_airline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
